version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  celery_worker:
    build: ./backend
    command: python celery_worker.py
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000" 